### ISSUE TITLE
Add a better installation framework.

### ISSUE THREAD

**Issue by jfarid27** [wildart/TDA.jl#3]
I believe the toml is fine but following the instructions in the readme produces some errors. The git syntax uses `#` when I think it should be `@` for the SmithNormalForm package. Could we streamline this a bit? It's likely those aren't even needed since it's specified in the project deps.

**Comment by wildart** [comment]
In the future, most of the packages will be in some registry, and installation will be reduced to installation of only `TDA.jl` package.

**Comment by jfarid27** [comment]
It's actually working with #4 . I was able to just add the package and get all the deps following the instructions updated in the README.

**Comment by jfarid27** [comment]
So @wildart I actually looked into this more. My PRs are actually breaking because just using `add {MyCoolPackageName}` only loads the dependencies if they're registered in the Julia Registry. Until each package is added to the Registry, none of the PRs will work. Another option is to create a new registry that a user can add to themselves.

I could ask around for what possible Registry options are available. It used to be that you add a PR to their Registry repo and it JustWorks after it's merged, but there don't seem to be instructions on it after the v1.0 bump. Maybe manually adding each package is the only option?

**Comment by wildart** [comment]
>  Another option is to create a new registry that a user can add to themselves.

I prefer this approach. I'll research a registry creation procedure as Julia 1.1 already out with the extended registry support in Pkg.

**Comment by wildart** [comment]
>  Another option is to create a new registry that a user can add to themselves.

I prefer this approach. I'll research a registry creation procedure as Julia 1.1 already out with the extended registry support in Pkg.

**Comment by wildart** [comment]
See #1
