### ISSUE TITLE
Relation with Eirene.jl?

### ISSUE THREAD

**Issue by juliohm** [wildart/TDA.jl#5]
Thanks @wildart for the package. Just sharing another package in case you are not aware. @Eetion has created Eirene.jl for persistence homology: https://github.com/Eetion/Eirene.jl

It would be nice to see a joint effort, I am excited to see these packages in Julia :)

Cheers,

**Comment by henselman-petrusek** [comment]
Thanks, @juliohm, it's nice to see community involvement in TDA.  Glad to chat, if interested @wildart.  :)

**Comment by wildart** [comment]
@juliohm I found about Eirene.jl when @Eetion mentioned it at his presentation at GC CUNY  couple of weeks ago. Good job @Eetion :+1: !

I stated some time ago fiddling with basic computational homology in my own package [ComputationalHomology.jl](https://github.com/wildart/ComputationalHomology.jl), and realized that there is no proper visualization toolkit for PH primitives.

That is how I see the goal of this package. So, please share your thoughts  on development of JuliaTDA community here or on https://discourse.julialang.org/

**Comment by juliohm** [comment]
Nice! I just wanted to make sure that you guys are aware of each other's work. Always good to see communities building up and producing a single robust framework as opposed to a bunch of incomplete packages :) That is the Julia spirit!

Closing the issue. Thanks.
